config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :personals
  devise_for :clients

  resources :appointments, only: %i[index show new create edit update] do
    resources :order_appointments, only: [:create]
    member do
      put 'appointments/:id', to: 'appointments#cancel', as: :cancel
    end
  end

  resources :order_appointments, only: [:index, :show]

  resources :clients, only: [] do
    resources :ordered_appointments, only: :index, module: :clients
  end

  resources :subsidiaries, only: :show do
    post 'enrolls/confirm', to: 'enrolls#confirm'
    resources :enrolls, only: :new
    get 'search', on: :collection
    resources :personals, only: [] do
      post 'add', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :clients, only: %i[index show]
      post 'users/:cpf/ban', to: 'users#ban', as: 'user_ban'
    end
  end

  resources :enrolls, only: :create
  resources :profiles, only: [:index, :show, :new,:create, :edit, :update]
end

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a href="/" class="navbar-brand"><%= image_tag('logo.png', class: 'logo') %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= render partial: 'subsidiaries/search' %>
    </ul>
    <ul class="navbar-nav ml-auto pr-5 mr-5">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if client_signed_in? %>
            <%= link_to 'Editar Cadastro', edit_client_registration_path, class: "dropdown-item" %>
            <%= link_to 'Sair', destroy_client_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to 'Personais disponíveis', order_appointments_path, class: "dropdown-item" %>
            <%= link_to 'Treinos agendados', client_ordered_appointments_path(current_client), class: "dropdown-item" %>
          <% elsif personal_signed_in? %>
            <%= link_to 'Editar Cadastro', edit_personal_registration_path, class: "dropdown-item" %>
            <%= link_to 'Sair', destroy_personal_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to 'Minha Agenda', appointments_path, class: "dropdown-item" if personal_signed_in? %>
          <%  else %>
            <%= link_to 'Registrar', new_client_registration_path, class: "dropdown-item" %>
            <%= link_to 'Entrar', new_client_session_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>

    </ul>
  </div>
</nav>