config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :personals
  devise_for :clients

  resources :appointments, only: %i[index show new create edit update] do
    resources :order_appointments, only: [:create]
    member do
      put 'appointments/:id', to: 'appointments#cancel', as: :cancel
    end
  end

  resources :order_appointments, only: [:index, :show]

  resources :clients, only: [] do
    resources :ordered_appointments, only: :index, module: :clients
  end

  resources :subsidiaries, only: :show do
    post 'enrolls/confirm', to: 'enrolls#confirm'
    resources :enrolls, only: :new
    get 'search', on: :collection
    resources :personals, only: [] do
      post 'add', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :clients, only: %i[index show]
      post 'users/:cpf/ban', to: 'users#ban', as: 'user_ban'
    end
  end

  resources :enrolls, only: :create
  resources :profiles, only: [:index, :show, :new,:create, :edit, :update]
end

app/models/subsidiary.rb
class Subsidiary
  attr_reader :id, :name, :address, :cnpj, :token

  def initialize(id:, name:, address:, cnpj:, token:)
    @id = id
    @name = name
    @address = address
    @cnpj = cnpj
    @token = token
  end

  def self.all
    response = Faraday.get "#{Rails.configuration.apis['subsidiaries']}/subsidiaries"

    if response.status == 200
      list = JSON.parse(response.body, symbolize_names: true)
      list.map do |item|
        new(id: item[:id], name: item[:name],
            address: item[:address], cnpj: item[:cnpj], token: item[:token])
      end
    else
      []
    end
  end

  def self.find(id)
    id = id.to_i
    all.find { |hash| hash.id == id }
  end

  def plans
    response = Faraday.get("#{Rails.configuration.apis[:subsidiaries]}subsidiaries/#{id}")
    if response.status == 200
      json = JSON.parse(response.body, symbolize_names: true)
      json[:subsidiary_plans].map do |item|
        Plan.new(**item, subsidiary: json[:id])
      end
    else
      []
    end
  end

  def self.search(query)
    all.filter do |subsidiary|
      subsidiary.name.downcase.include?(query.downcase) or
        subsidiary.address.downcase.include?(query.downcase)
    end
  end

  private

  def mocked_plans
    plans = []
    plans << Plan.new(id: 1, name: 'Default', monthly_payment: 120, permanency: 12, subsidiary: self)
    plans
  end

  def api_plans
    response = Faraday.get("#{id}/api/plans")
    if response.status == 200
      JSON.parse(response.body, symbolize_names: true).map do |item|
        Plan.new(**{ **item, subsidiary: id })
      end
    else
      []
    end
  end
end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController
  def show
    @subsidiary = Subsidiary.find(params[:id])
    add_breadcrumb(@subsidiary.name)
  end

  def search
    add_breadcrumb('Busca')
    @subsidiaries = Subsidiary.search(params[:q])
  end
end

app/views/subsidiaries/_search.html.erb
<div class="my-2 my-lg-0 ml-auto text-white">
  <%= form_with url: search_subsidiaries_path, method: :get, local: true, html: { class: 'form-inline' } do |f| %>
    <div class="form-group mx-3">
      <%= f.label :q, 'Busca de filiais', class: 'mx-3' %>
      <%= f.text_field :q, class: "form-control mr-sm-2" %>
    </div>
    <%= f.submit t('.submit'), class: "btn btn-custom my-2 my-sm-0" %>
  <% end %>
</div>

app/views/subsidiaries/search.html.erb
<% if @subsidiaries.empty? %>
  <h2>Nenhuma filial encontrada</h2>
<% else %>
  <% @subsidiaries.each do |subsidiary| %>
    <div>
      <h2><%= link_to subsidiary.name, subsidiary_path(subsidiary.id) %></h2>
      <li><%= subsidiary.address %></li>
    </div>
  <% end %>
<% end %>

app/views/subsidiaries/show.html.erb
<section class="subsidiary_details">
  <div class="card bg-dark text-white">
    <%= image_tag('subsidiaries.jpg', class: 'card-img') %>
    <div class="card-img-overlay subsidiary_details_card">
      <h5 class="card-title">Unidade <%= @subsidiary.name %></h5>
      <p class="card-text">Lorem ipsum</p>
      <p class="card-text"><%= @subsidiary.address %></p>
      <% if personal_signed_in? %>
        <%= button_to 'Adicionar Filial', add_subsidiary_personal_path(@subsidiary.id, current_personal), class: 'custom-button' %>
      <% end %>

      <% if !client_signed_in? || !current_client.already_enrolled? %>
        <%= link_to t('.enroll_now'), new_subsidiary_enroll_path(@subsidiary.id), class: 'custom-button' %>
      <% end %>
    </div>
  </div>


</section>