config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :personals
  devise_for :clients

  resources :appointments, only: %i[index show new create edit update] do
    resources :order_appointments, only: [:create]
    member do
      put 'appointments/:id', to: 'appointments#cancel', as: :cancel
    end
  end

  resources :order_appointments, only: [:index, :show]

  resources :clients, only: [] do
    resources :ordered_appointments, only: :index, module: :clients
  end

  resources :subsidiaries, only: :show do
    post 'enrolls/confirm', to: 'enrolls#confirm'
    resources :enrolls, only: :new
    get 'search', on: :collection
    resources :personals, only: [] do
      post 'add', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :clients, only: %i[index show]
      post 'users/:cpf/ban', to: 'users#ban', as: 'user_ban'
    end
  end

  resources :enrolls, only: :create
  resources :profiles, only: [:index, :show, :new,:create, :edit, :update]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @subsidiaries = Subsidiary.all
  end
end

app/views/home/index.html.erb
<section class="home">
  <section class="home_banner">
    <h1>ESPERTO FIT</h1>
    <h3>Transforme sua vida com conhecimento</h3>
    <a class= "home_discover_button" href="#subsidiaries">Comece-já</a>
  </section>

  <section class="home_subsidiaries">
    <% if client_signed_in? && current_client.enroll.present? %>
      <div>
        <% if current_client.profile.nil?%>
          <%= link_to 'Complete seu perfil', new_profile_path, class: 'btn btn-primary' %>
        <% else %>
          <%= link_to 'Meu perfil', profile_path(current_client.profile), class: 'btn btn-primary' %>
        <% end %>
      </div>
    <% end %>

    <% if personal_signed_in? %>
      <p>Bem vindo, <%= current_personal.name %>!</p>
    <% end %>

    <h2 id="subsidiaries" class="home_subsidiaries_text">Conheça nossas Unidades</h2>


    <% if @subsidiaries.empty? %>
      <h1>Nenhuma filial encontrada</h1>
    <% else %>
      <% @subsidiaries.each do |subsidiary| %>
       <div class="card" style="width: 18rem;">
         <%= image_tag('subsidiaries.jpg', class: "card-img-top") %>
         <div class="card-body">
           <h5 class="card-title"><%= link_to subsidiary.name, subsidiary_path(subsidiary.id)%></h5>
           <p class="card-text"><%= subsidiary.address %></p>
           <%= link_to 'Veja mais', subsidiary_path(subsidiary.id), class: 'btn btn-custom' %>
         </div>
       </div> 
      <% end %>
    <% end %>
  </section>
</section>